version: '2'
services:
  apache:
    build: .
    image: patsys/samba
  sut:
    image: patsys/test-webserver
    depends_on:
      - apache 
    environment:
      - HOST=apache
      - WORD="PHP Version"
      - INTERVAL=5
      - TRY=30
