version: '2'
services:
  apache:
    build: .
    image: patsys/apache
  sut:
    image: patsys/test-webserver
    depends_on:
      - apache 
    environment:
      - HOST=apache
      - WORD=System
      - INTERVAL=5
      - TRY=30
